### ISSUE TITLE
log4j:WARN Please initialize the log4j system properly.

### ISSUE THREAD

**Issue by nyxjemk** [iesl/conll2012-preprocess-parsing#1]
Hey - I'm trying to follow the steps in the readme, but during the pre-possessing step I'm getting this java error:

```
POS tagging: ../conll-2012/v4/data/train/data/english/annotations
log4j:WARN No appenders could be found for logger (edu.emory.clir.clearnlp.util.BinUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

Any Idea how I can solve this resp. how I can initialize the log4j system properly?

**Comment by strubell** [comment]
This is a clearnlp warning, which shouldn't be a problem.

The documentation for this repo may not be up to date -- may I ask what you're using this repo for?

**Comment by nyxjemk** [comment]
I was looking for a tool that converts the onto notes corpus to a special format, but it turned that I need something completely different. 

Sorry for bothering you and thx for your help!

**Comment by strubell** [comment]
Ah ok, no problem!
